image:
  registry: ghcr.io
  repository: maxherbs/hive-metrics-otel-proxy
  tag: ""
  pullPolicy: IfNotPresent

deployment:
  port: 80
  metricsConfig:
    - name: temperature
      unit: celsius
      description: Current temperature
    - name: humidity
      unit: percentage
  replicas: 1
  annotations: []
  podAnnotations: []
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  nodeSelector: {}
  affinity: {}
  tolerations: []

service:
  create: true
  annotations: []
  type: ClusterIP
  port: 80

ingress:
  create: true
  className: traefik
  host: hive-proxy.theoffice.uk


opentelemetry-collector:
  image:
    repository: otel/opentelemetry-collector-contrib
  mode: deployment
  ports:
    prometheus:
      enabled: true
      containerPort: 9090
      servicePort: 9090
      protocol: TCP

  config:
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
    exporters:
      prometheus:
        endpoint: 0.0.0.0:9090
      # debug: {}
    service:
      pipelines:
        metrics:
          receivers:
            - otlp
          exporters:
            - prometheus
            # - debug
      # telemetry:
        # logs:
        #   level: "DEBUG"
        #   development: true
        #   encoding: "json"

prometheus:
  kube-state-metrics:
    enabled: false
  prometheus-node-exporter:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  alertmanager:
    enabled: false

  serverFiles:
    prometheus.yml:
      scrape_configs:
      - job_name: 'Prometheus'
        scrape_interval: 5y
        static_configs:
          - targets: ['localhost:9090']
  server:
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - hive-prometheus.theoffice.uk
  extraScrapeConfigs: |
    - job_name: 'otel-collector'
      scrape_interval: 30s
      scrape_timeout: 30s
      static_configs:
        - targets:
            - "{{ .Release.Name }}-opentelemetry-collector:9090"

grafana:
  enabled: true
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ingress:
    enabled: true
    ingressClassName: "traefik"
    hosts:
      - hive-grafana.theoffice.uk
  grafana.ini:
    auth:
      disable_login_form: true
    auth.anonymous:
      enabled: true
      org_name: Main Org.
      org_role: Admin
  adminPassword: admin
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          uid: webstore-metrics
          type: prometheus
          url: "http://{{ .Release.Name }}-prometheus-server:80"
          isDefault: true
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
  dashboardsConfigMaps:
    default: grafana-dashboards
