# Changes here will be overwritten by Copier
_commit: 2.6.0
_src_path: gh:DiamondLightSource/python-copier-template
author_email: max@maxherbert.com
author_name: Max Herbert
description: 'Proxy API to convert simplified JSON packages from IOT devices to OTLP-compliant
    metrics bodies '
distribution_name: otel-proxy
docker: true
docs_type: README
git_platform: github.com
github_org: maxherbs
package_name: otel_proxy
pypi: false
repo_name: otel-proxy
type_checker: pyright
