apiVersion: v2
name: hive-metrics
description: Central deployment for metrics platform
type: application

version: 0.1.0

dependencies:
  - name: prometheus
    repository: https://prometheus-community.github.io/helm-charts
    version: 27.4.0
  - name: opentelemetry-collector
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.114.0
  - name: grafana
    version: 8.10.1
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
