replicaCount: 1

otel_endpoint: "http://hive-metrics-opentelemetry-collector.hive.svc.cluster.local:4318/v1/metrics"
metricsConfig:
  - name: temperature
    unit: celsius
    description: Current temperature
  - name: humidity
    unit: percentage

image:
  registry: ghcr.io
  repository: maxherbs/hive-metrics-otel-proxy
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: traefik
  annotations: {}
  hosts:
    - host: hive-proxy.theoffice.uk
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /healthz
    port: http
readinessProbe:
  httpGet:
    path: /healthz
    port: http

volumes: []
volumeMounts: []
tolerations: []
affinity: {}


oauth2-proxy:
  enabled: true
  replicaCount: 1
  ingress:
    enabled: true
    pathType: Prefix
    hosts:
      - proxy.theoffice.uk
    path: /
  config:
    configFile: |-
      email_domains = [
        "*"
      ]
      skip_provider_button = true
  alphaConfig:
    enabled: true
    configFile: |-
      upstreamConfig:
        upstreams:
          - id: gateway
            path: /
            uri: http://otel-proxy:80
    configData:
      injectRequestHeaders:
        - name: X-Client-ID
          values:
            - claim: azp
      providers:
        - provider: oidc
          scope: "openid"
          clientId: proxy
          clientSecretFile: /etc/alpha/secret
          id: authn
          oidcConfig:
            issuerURL: https://authn.theoffice.uk/realms/master
            insecureAllowUnverifiedEmail: true
            audienceClaims:
              - aud
            emailClaim: email
  extraArgs:
    - --cookie-refresh=55s
  extraVolumes:
    - name: secret
      secret:
        secretName: proxy-sso
        items:
          - key: secret
            path: secret
  extraVolumeMounts:
    - name: secret
      mountPath: /etc/alpha
      readOnly: true

