on:
  workflow_call:

jobs:
  run:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install otel-proxy
        run: |
          pip install ./otel-proxy[dev]

      - name: Run lint
        run: |
          cd otel-proxy
          ruff check
          ruff format
