name: otel-proxy-tests

on:
  workflow_call:

env:
  SETUPTOOLS_SCM_PRETEND_VERSION: 1.2.3


jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install package
        run: pip install ./otel-proxy[dev]

      - name: Run tests
        run: |
          cd otel-proxy
          pytest tests/