name: otel-proxy-tests

on:
  workflow_call:

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install package
        run: pip install ./otel-proxy[dev]

      - name: Run tests
        run: |
          cd otel-proxy
          pytest tests/