name: otel-proxy test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1.12.0
        with:
          cache: false
          components: clippy,rustfmt

      - uses: actions/cache@v4
        with:
          path: |
            ./otel-proxy/target
          key: rust-test

      - name: Run test
        working-directory: otel-proxy
        run: cargo test
