services:
  otel-proxy:
    build:
      context: ..
      dockerfile: ./Dockerfile
      target: developer
    volumes:
      - ./..:/workspace:cached,z
    command: sleep infinity
    environment:
    - OTEL_URL="http://otel-collector:4318/v1/metrics"
    - SETUPTOOLS_SCM_PRETEND_VERSION=1.2.3


  otel-collector:
    image: docker.io/otel/opentelemetry-collector-contrib:latest 
    restart: unless-stopped
    environment:
      - OTEL_LOG_LEVEL=debug
    ports:
      - "4318:4318"
      - "4317:4317" 
      - "9090:9090" 
    volumes:
      - ./../:/workspace
    command: "--config /workspace/.devcontainer/otel-config.yaml"

  prometheus:
    depends_on: [ otel-collector ]
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./../:/workspace
    command: "--config.file=/workspace/.devcontainer/prometheus.yml"
